blank_issues_enabled: false
contact_links:
  - name: Rivercord Support Server
    url: https://discord.gg/D9uwnFnqmd
    about: If you need help regarding Rivercord, please join our support server!
  - name: Rivercord Installer
    url: https://github.com/Rivercord/Installer
    about: You can find the Rivercord Installer here
